### PR TITLE
Fix/bug fixes

### LINKED ISSUE #191: Fix bugs on prod
# Bugs
Since the new version was uploaded to prod there where 3 bugs found that need to be fixed:
- [x] The legend and hours of the schedule on the print aren't displayed when the dark theme is activated neither the background is dark;
- [x] The paste feature isn't working on Microsoft Edge probably due to the same reason it wasn't working on on Firefox;
- [x] The random schedule feature has some bugs
- [x] There also are some console.log that weren't deleted that should be deleted;

### PR DESCRIPTION
**Pull request by diogotvf7**
# What was done: 

## Bugfixes:
- The legend and hours of the schedule on the print weren't being displayed when the dark theme was activated neither the background was dark. Now it works as expected;
- The paste feature was only working for Firefox, now it works for every browser;
- The random schedule feature had some bugs that are now fixed;
## Enhance:
- There also are some console.log that weren't deleted that should be deleted;
- Some tooltips were added to buttons briefly explaining their functionality;
- The order by which courses appear now is the same as sigarra's

Closes #191

### CODE REVIEW

File: src/api/storage.ts [hunk 1]
```diff
@@ -58,6 +56,7 @@ const getOptionsStorage = (): MultipleOptions => {
       return courseOptions
 
     } else {
+      console.log('Invalid storage')
```
Comment (tomaspalma) [inline src/api/storage.ts:59]: Maybe this console.log as well, since it is not relevant to the user that the storage is invalid, since the application will self heal by resetting the localstorage.

File: src/pages/TimeTableScheduler.tsx [hunk 2]
```diff
@@ -397,6 +395,8 @@ const TimeTableSchedulerPage = () => {
     setCheckedCourses(newCheckedCourses)
   }
 
+  console.log(multipleOptions)
+
```
Comment (tomaspalma) [inline src/pages/TimeTableScheduler.tsx:399]: Maybe you should also remove this console.log

**Review by tomaspalma — CHANGES_REQUESTED** [review]
The rest looks god :rocket:

File: src/pages/TimeTableScheduler.tsx (hunk 2 above)
Comment (diogotvf7) [reply src/pages/TimeTableScheduler.tsx:399]: oopss

File: src/api/storage.ts (hunk 1 above)
Comment (diogotvf7) [reply src/api/storage.ts:59]: done!

**Review by tomaspalma — APPROVED** [review]
LGTM :rocket:

**Review by thePeras — APPROVED** [review]
✅ 🛫
