### PR TITLE
Fixed No Data Message Admin

### LINKED ISSUE #559: Show “No requests found” message
When there are no requests in a tab, display a clear message instead of leaving the section blank.
This behavior currently only exists in the “Student Exchanges” tab and should be extended to all tabs.

### PR DESCRIPTION
**Pull request by matilde-sousa**
Added informative messages when there is nothing to be displayed in Exchanges and Enrollments in Admin section.

Closes  #559

### CODE REVIEW

File: src/components/admin/requests/AdminMarketplaceExhanges.tsx [hunk 1]
```diff
@@ -13,6 +13,10 @@ export const AdminMarketplaceExhanges = () => {
     return (<>
         {loading && <BarLoader className="w-full" />}
 
+        {!loading && (!exchanges || exchanges.length === 0) && (
+                    <h2>Nenhuma pedido encontrado de momento</h2>
```
Comment (jose-carlos-sousa) [inline src/components/admin/requests/AdminMarketplaceExhanges.tsx]: Change to "Nenhuma" to "Nenhum" and remove extra tab in line 18(not sure why the linter didn't complain)

**Review by jose-carlos-sousa — APPROVED** [review]
LGTM feel free to merge
